#!/bin/sh

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

echo "$FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write

echo -e "\nValidating Javascript & Typescript with eslint:"

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.jsx?$|\.tsx?$|\.js$|\.ts$")

if [ -n "$STAGED_FILES" ]; then
  ESLINT_OUTPUT=$(echo "$STAGED_FILES" | xargs ./node_modules/.bin/eslint --fix --format json)
  
  if echo "$ESLINT_OUTPUT" | grep -q '"errorCount": [1-9]'; then
    echo -e "ESLint found errors, aborting commit."
    echo "$ESLINT_OUTPUT" | ./node_modules/.bin/eslint-formatter-friendly
    exit 1
  else
    echo -e "ESLint validation completed successfully."
  fi
fi

echo -e "\nValidating TypeScript compilation:"
TS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E  "\.tsx?$|\.ts$")

if [ -n "$TS_FILES" ]; then
  for FILE in $TS_FILES
  do
    ./node_modules/.bin/tsc --noEmit "$FILE"
    if [ $? -ne 0 ]; then
      echo -e "TypeScript compilation failed for $FILE, aborting commit."
      exit 1
    fi
  done
fi

echo -e "\nValidating JavaScript compilation:"
JS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.jsx?$|\.js$")

if [ -n "$JS_FILES" ]; then
  for FILE in $JS_FILES
  do
    node --check "$FILE"
    if [ $? -ne 0 ]; then
      echo -e "JavaScript compilation failed for $FILE, aborting commit."
      exit 1
    fi
  done
fi

echo -e "\nValidating TSX compilation:"
TSX_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.tsx?$")

if [ -n "$TSX_FILES" ]; then
  for FILE in $TSX_FILES
  do
    ./node_modules/.bin/tsc --noEmit "$FILE"
    if [ $? -ne 0 ]; then
      echo -e "TSX compilation failed for $FILE, aborting commit."
      exit 1
    fi
  done
fi

echo "$FILES" | xargs git add
echo "$STAGED_FILES" | xargs git add

exit 0
